default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vlad
  password: secret
  host: localhost
  port: 5432

development:
  <<: *default
  database: devise_jwt_app

test:
  <<: *default
  database: devise_jwt_app_test
